### ISSUE TITLE
Date values don't need quotes

### ISSUE THREAD

**Issue by ccudennec-otto** [asyncapi/studio#1119]
#### Describe the bug
My schema contains a string property with format "date":
```
       - type: "object"
          properties:
            appointmentDate:
              type: "string"
              format: "date"
```

The file also contains an example for this property:

```
examples:
- appointmentDate: 2015-07-20
```

If the value is not quoted, I can see the following error in the "Diagnostics" section of https://studio.asyncapi.com/

```
"appointmentDate" property must match format "date"
```

If I read the [YAML specification](https://yaml.org/spec/1.2.2/#plain-style) correctly, the above value does not need quotes to be interpreted as a valid string.

#### How to Reproduce
Described above.

#### Expected behavior
I don't see an error if the value is not quoted.

For your information:
I've also created an issue in the library that I use the generate the asyncapi.yaml to go around this: https://github.com/springwolf/springwolf-core/issues/820

But in general IMHO the core issue is that AsyncAPI Studio should not mark unquoted values as error.
