### ISSUE TITLE
Import document with $ref not able to resolve

### ISSUE THREAD

**Issue by LittleWat** [asyncapi/studio#599]
relative issue: https://github.com/asyncapi-archived-repos/playground/issues/30

#### Describe the bug
cannot resolve the relative path of payload `$ref`

#### How to Reproduce

```yaml
asyncapi: 2.0.0
....
channels:
  test:
    subscribe:
      message:
        name: test
        title: test
        contentType: avro/binary
        schemaFormat: application/vnd.apache.avro+json;version=1.9.0
        payload:
          ## This works
          #$ref: "https://raw.githubusercontent.com/Apicurio/apicurio-registry-examples/main/simple-avro-maven/src/main/resources/schemas/greeting.avsc"

          # this does not work...
         $ref: "../../../greeting-schema.avsc"

```
#### Expected behavior
can resolve the relative path of payload `$ref`

Is this feature supported?  `$ asyncapi start studio` gets error...
Any ideas are welcome, thank you!

**Comment by JFCote** [comment]
I have the same problem trying to load my model which are in another file. The other file is in the same folder of my base asyncapi.yaml file so access should not be a problem.

```yaml
channels:
  status-changed:
    subscribe:
      operationId: emitStatusChanged
      message:
        $ref: './models.yaml#/components/messages/StatusChanged'
```

I started the studio with this command:

`asyncapi start studio -f asyncapi.yaml`

Expected behavior would be to follow the ref, especially if they are easily accessible like being in the same folder.
