### ISSUE TITLE
Studio showing errors that are not really there

### ISSUE THREAD

**Issue by derberg** [asyncapi/studio#887]
#### Describe the bug

Studio shows errors that are not errors (however strange it sounds). I do know if it is issue related to parser only or some wrong interpretation of parser errors in studio.

#### How to Reproduce

Open https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/spec/d78dcea70c9b094a3df72f9a4e811828cec778cc/examples/adeo-kafka-request-reply-asyncapi.yml and you will see some errors that you try to investigate but "they are not really there" - I mean they do not really are problems, and do not need to be solved.

There is only one valid issue with this file, lines 242-245

```
      bindings:
        kafka:
          key:
            $ref: "https://deploy-preview-921--asyncapi-website.netlify.app/resources/casestudies/adeo/CostingResponseKey.avsc"
```

If you remove above. There are all suddenly no errors anymore  and docs get rendered. This issue is related to: https://github.com/asyncapi/spec-json-schemas/pull/466

#### Expected behavior

I should see that my yaml has error in line 245, that I'm referencing file in wrong format
