### ISSUE TITLE
security and securitySchemes do not recognize apiKey or httpApiKey types

### ISSUE THREAD

**Issue by nicolasmohamed** [asyncapi/studio#914]
#### Describe the bug

If type field equals to apiKey, AsyncAPI Studio shows the following error:

_"type" property must be equal to one of the allowed values: "userPassword", "X509", "http", "httpApiKey", "oauth2", "openIdConnect". Did you mean "httpApiKey"?_

If type field equals to httpApiKey, AsyncAPI Studio shows the following error:

_"type" property must be equal to one of the allowed values: "userPassword", "apiKey", "http", "oauth2", "openIdConnect". Did you mean "apiKey"?_

#### How to Reproduce
```
securitySchemes:
    EventGridDomainKey:
      type: apiKey

securitySchemes:
    EventGridDomainKey:
      type: httpApiKey
```

same for:

```
security:
  - type: apiKey
```

#### Expected behavior
AsyncAPI Studio should render correctly as apiKey and httpApiKey are both valid types.

Thanks!!
